services:
  php:
    container_name: imdhemy_php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    volumes:
      - ./:/app
      - imdhemy_caddy_data:/data
      - imdhemy_caddy_config:/config

volumes:
  imdhemy_caddy_data:
  imdhemy_caddy_config:
